#!/usr/bin/env python3
"""
Generate Triton model repository entries from config/models.yaml.

Usage
-----
    python scripts/setup_model_repo.py [--config PATH] [--output-dir PATH]

This script reads the model configuration and writes a ``config.pbtxt`` and
``1/model.json`` for each model into the target model repository directory.
Existing files are overwritten so the repository stays in sync with the YAML.

Run this script once before starting the Triton server and again any time you
add or change a model in models.yaml.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path

# Allow running directly from repo root without installing the package.
_REPO_ROOT = Path(__file__).parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

import yaml  # noqa: E402 – must come after sys.path is patched

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger(__name__)

_CONFIG_PBTXT_TEMPLATE = """\
# Auto-generated by scripts/setup_model_repo.py – do not edit manually.
# Model: {model_name}
# Description: {description}

backend: "vllm"

instance_group [
  {{
    count: 1
    kind: KIND_MODEL
  }}
]
"""


def generate_model_json(spec: dict) -> dict:
    """Build the vLLM engine arguments dict from a model spec."""
    return {
        "model": spec["model_path"],
        "gpu_memory_utilization": float(spec.get("gpu_memory_utilization", 0.85)),
        "tensor_parallel_size": int(spec.get("tensor_parallel_size", 1)),
        "enforce_eager": bool(spec.get("enforce_eager", False)),
        "disable_log_requests": True,
    }


def setup_model_repo(config_path: Path, output_dir: Path) -> None:
    with config_path.open() as fh:
        raw = yaml.safe_load(fh)

    models = raw.get("models") or {}
    if not models:
        logger.warning("No models found in %s", config_path)
        return

    output_dir.mkdir(parents=True, exist_ok=True)

    for model_name, spec in models.items():
        model_dir = output_dir / model_name
        version_dir = model_dir / "1"
        version_dir.mkdir(parents=True, exist_ok=True)

        # Write config.pbtxt
        config_pbtxt = _CONFIG_PBTXT_TEMPLATE.format(
            model_name=model_name,
            description=spec.get("description", ""),
        )
        config_path_out = model_dir / "config.pbtxt"
        config_path_out.write_text(config_pbtxt)
        logger.info("Wrote %s", config_path_out)

        # Write 1/model.json
        model_json = generate_model_json(spec)
        model_json_path = version_dir / "model.json"
        model_json_path.write_text(json.dumps(model_json, indent=4) + "\n")
        logger.info("Wrote %s", model_json_path)

    logger.info(
        "Model repository set up at %s with %d model(s).", output_dir, len(models)
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Triton model repository from models.yaml"
    )
    repo_root = Path(__file__).parent.parent
    parser.add_argument(
        "--config",
        default=str(repo_root / "config" / "models.yaml"),
        help="Path to models.yaml (default: config/models.yaml)",
    )
    parser.add_argument(
        "--output-dir",
        default=str(repo_root / "model_repository"),
        help="Destination model repository directory (default: model_repository/)",
    )
    args = parser.parse_args()

    setup_model_repo(Path(args.config), Path(args.output_dir))


if __name__ == "__main__":
    main()
